### ISSUE TITLE
UnsatisfiedLinkError: library "libjingle_peerconnection_so.so" not found

### ISSUE THREAD

**Issue by dkrivoruchko** [webrtc-sdk/android#16]
Keep getting `UnsatisfiedLinkError: dlopen failed: library "libjingle_peerconnection_so.so" not found` on production for Android from 8 to 13. 
Version 114.5735.02

**Comment by urko-b** [comment]
same here

**Comment by urko-b** [comment]
Solved **[here](https://github.com/webrtc-sdk/android/issues/20#issuecomment-1929126213)**
