### ISSUE TITLE
How should I use frame encryption on Android, is there any demo code？

### ISSUE THREAD

**Issue by fushui99** [webrtc-sdk/android#19]

**Comment by Tunshutegong** [comment]
> _No description provided._

Hello, I have encountered the same problem. Do you know how to use it now

**Comment by davidzhao** [comment]
FrameCryptor is fairly low level. We use this functionality in LiveKit's SDKs. 

Here's the implementation in Android: https://github.com/livekit/client-sdk-android/blob/main/livekit-android-sdk/src/main/java/io/livekit/android/e2ee/E2EEManager.kt

and example app usage: https://github.com/livekit/client-sdk-android/blob/ce0cb61619d8cc78376566d0bf8e10e493c45612/sample-app-common/src/main/java/io/livekit/android/sample/CallViewModel.kt#L90
