### ISSUE TITLE
commit hash for 92.4515.01?

### ISSUE THREAD

**Issue by davidliu** [webrtc-sdk/android#2]
Hey @cloudwebrtc, what's the commit hash for the [92.4515.01](https://github.com/webrtc-sdk/android/releases/tag/92.4515.01) release? It doesn't seem like it's built off of the webrtc-sdk/webrtc project, so I want to make sure we're not backtracking by making new releases from that source.

**Comment by cloudwebrtc** [comment]
hey @davidliu, I think we need to recompile and release a new version. The current version is made by me trying to test the `jitpack` release.

**Comment by cloudwebrtc** [comment]
This 92.4515.01 was built locally a month ago. The source code should be inconsistent with the main branch of `webrtc-sdk/webrtc`, so we need to use the latest commit to compile again.

In addition, we can try to build using GitHub actions, which will be triggered when we release a new tag.
