### ISSUE TITLE
104.5112.03 aar is removed from jitpack

### ISSUE THREAD

**Issue by linsui** [webrtc-sdk/android#7]
https://jitpack.io/com/github/webrtc-sdk/android/104.5112.03

Is this a bug of JitPack.io?

**Comment by cloudwebrtc** [comment]
It seems yes, 104.5112.03 has been available for download since October, until these days several issue reports could not be downloaded

**Comment by linsui** [comment]
@jitpack Could you please take a look? Thanks!

**Comment by JcMinarro** [comment]
A maintainer of this project (I think @cloudwebrtc or @davidliu) should be able to re-run the build process to have this artifact ready on @jitpack again.
You will need to go to https://jitpack.io/#webrtc-sdk/android/104.5112.03 login with your Github Account and you should see an option to re-run the build process

**Comment by davidliu** [comment]
Hmm, I'm not sure there's much we can do from our end. Builds are frozen after 7 days and we can't re-run the build process any more.

Looks like there's an issue with JitPack:

https://github.com/jitpack/jitpack.io/issues/5289

**Comment by davidliu** [comment]
A mirror of 104.5112.03 is uploaded to Maven Central.
```
  dependencies {
    implementation 'io.github.webrtc-sdk:android:104.5112.03'
  }
```
