### ISSUE TITLE
Open source compile scripts?

### ISSUE THREAD

**Issue by BenniHackstock** [webrtc-sdk/android#8]
First of all, huge thanks for the compiled binaries, it's a big help for the app I'm developing ❤️

The situation (and request) I have is the following: 
we would like to make some small adjustment to the sourcecode, but haven't gotten around to writing the scrips/logic that compiles `webrtc` for android ourselves.

Would you consider open-sourcing the build scripts you use?
If there is something I can help with, please let me know

**Comment by davidzhao** [comment]
The build scripts are [here](https://github.com/webrtc-sdk/webrtc-build). Take a look at the [CI workflows](https://github.com/webrtc-sdk/webrtc-build/blob/main/.github/workflows/build.yml) for how they could be run.
